/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forma;

import domen.Ispit;
import domen.PrijavaIspita;
import domen.RacunPrijaveIspita;
import domen.Student;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.KlijentKontroler;
import model.ModelTabelePrijava;

/**
 *
 * @author mihailomitrovic
 */
public class FormaPretragaPrijava extends javax.swing.JDialog {

    private static String poruka = "";

    public static void setPoruka(String poruka) {
        FormaPretragaPrijava.poruka = poruka;
    }
    
    /**
     * Creates new form FormaPretragePrijava
     */
    public FormaPretragaPrijava(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        btnResetuj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrijave = new javax.swing.JTable();
        btnIzdajRacun = new javax.swing.JButton();
        btnOdjaviIspit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Studentska služba - Prijave");

        jLabel1.setText("Ime i prezime studenta (ili naziv ispita):");

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnResetuj.setText("Resetuj");
        btnResetuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetujActionPerformed(evt);
            }
        });

        tblPrijave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrijave);

        btnIzdajRacun.setText("Izdaj račun");
        btnIzdajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzdajRacunActionPerformed(evt);
            }
        });

        btnOdjaviIspit.setText("Odjavi ispit");
        btnOdjaviIspit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviIspitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPretraga))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPretrazi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResetuj))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOdjaviIspit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIzdajRacun)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretrazi)
                    .addComponent(btnResetuj))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzdajRacun)
                    .addComponent(btnOdjaviIspit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        if (txtPretraga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite parametar za pretragu!");
            return;
        }
        
        try {
            Ispit i = new Ispit(-1, txtPretraga.getText(), "", 0, 0);
            Student s = new Student(-1, txtPretraga.getText(), new Date(), "", null);
            PrijavaIspita p = new PrijavaIspita(-1, new Date(), null, i, s, sesija.Sesija.getInstance().getUlogovani());
            ArrayList<PrijavaIspita> listaPronadjenih = KlijentKontroler.getInstance().nadjiPrijaveIspita(p);
            tblPrijave.setModel(new ModelTabelePrijava(listaPronadjenih));
            
            if (listaPronadjenih.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem ne može da nađe prijave po zadatoj vrednosti");
                    txtPretraga.setText(null);
                    ArrayList<PrijavaIspita> praznaLista = new ArrayList<>();
                    tblPrijave.setModel(new ModelTabelePrijava(praznaLista));
            } else {
                    JOptionPane.showMessageDialog(this, "Sistem je našao prijave po zadatoj vrednosti");
                    tblPrijave.setModel(new ModelTabelePrijava(listaPronadjenih));
            }     
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe prijave po zadatoj vrednosti");
        }
        
        txtPretraga.setText(null);
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnResetujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetujActionPerformed
        osveziTabelu();
    }//GEN-LAST:event_btnResetujActionPerformed

    private void btnOdjaviIspitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviIspitActionPerformed
        int red = tblPrijave.getSelectedRow();
        
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita prijavu! Izaberite red!");
            return;
        } else {            
            try {
                ModelTabelePrijava mtp = (ModelTabelePrijava) tblPrijave.getModel();
                PrijavaIspita prijava = mtp.getPrijava(red);
                
                PrijavaIspita p = new PrijavaIspita(prijava.getPrijavaID(), new Date(), null, null, null, null);
                PrijavaIspita parametar = KlijentKontroler.getInstance().ucitajPrijavuIspita(p);
                KlijentKontroler.getInstance().obrisiPrijavuIspita(parametar);
                
                Object[] opcije = { "Da", "Ne" };
                int izbor = JOptionPane.showOptionDialog(null, "Da li želite da obrišete prijavu?", "Brisanje prijave",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcije, opcije[0]);
                
                if (izbor == 0) {
                    try {
                        JOptionPane.showMessageDialog(this, "Sistem je obrisao prijavu!");
                        osveziTabelu();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Sistem ne može da obriše prijavu!");
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita prijavu!");
            }
        }
    }//GEN-LAST:event_btnOdjaviIspitActionPerformed

    private void btnIzdajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzdajRacunActionPerformed
        int red = tblPrijave.getSelectedRow();
        
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita prijavu! Izaberi red!");
            return;
        } else {
            try {                
                ModelTabelePrijava mtp = (ModelTabelePrijava) tblPrijave.getModel();
                PrijavaIspita prijava = mtp.getPrijava(red);
                
                PrijavaIspita p = new PrijavaIspita(prijava.getPrijavaID(), new Date(), null, null, null, null);
                PrijavaIspita parametar = KlijentKontroler.getInstance().ucitajPrijavuIspita(p);
                JOptionPane.showMessageDialog(this, "Sistem je učitao prijavu!");
                
                try {
                    RacunPrijaveIspita racun = KlijentKontroler.getInstance().vratiRacunPrijaveIspita(prijava);
                    
                    if (racun != null) {
                        JOptionPane.showMessageDialog(this, "Sistem je već kreirao račun za ovu prijavu!");
                        return;
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Sistem ne može da učita prijavu!");
                }
                
                Object[] opcije = { "Da", "Ne" };
                int izbor = JOptionPane.showOptionDialog(null, "Da li želite da izdate račun?", "Izdavanje računa",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcije, opcije[0]);
                
                if (izbor == 0) {
                    try {
                        JOptionPane.showMessageDialog(this, "Sistem nije ranije kreirao račun za ovu prijavu!");
                        FormaRacun forma = new FormaRacun(this, true, parametar);
                        forma.setVisible(true);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Sistem ne može da učita prijavu!");
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita prijavu!");
            }
        }
    }//GEN-LAST:event_btnIzdajRacunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaPrijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaPrijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaPrijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaPrijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormaPretragaPrijava dialog = new FormaPretragaPrijava(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzdajRacun;
    private javax.swing.JButton btnOdjaviIspit;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnResetuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrijave;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            tblPrijave.setModel(new ModelTabelePrijava());
        } catch (Exception ex) {
            Logger.getLogger(FormaPretragaPrijava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void osveziTabelu() {
        try {
            tblPrijave.setModel(new ModelTabelePrijava());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da osveži tabelu!");
        }
    }
}
