/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forma;

import domen.Student;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.KlijentKontroler;
import model.ModelTabeleStudent;

/**
 *
 * @author mihailomitrovic
 */
public class FormaPretragaStudenata extends javax.swing.JDialog {

    private static String poruka = "";

    public static void setPoruka(String poruka) {
        FormaPretragaStudenata.poruka = poruka;
    }
    
    /**
     * Creates new form FormaPretrageStudenata
     */
    public FormaPretragaStudenata(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        btnResetuj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudenti = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnPrijava = new javax.swing.JButton();
        txtPretraga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Studentska služba - Studenti");

        jLabel1.setText("Ime i prezime:");

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnResetuj.setText("Resetuj");
        btnResetuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetujActionPerformed(evt);
            }
        });

        tblStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStudenti);

        btnIzmeni.setText("Izmeni studenta");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrijava.setText("Prijavi ispit");
        btnPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijavaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPretraga))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPretrazi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResetuj))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnIzmeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrijava)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretrazi)
                    .addComponent(btnResetuj))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnPrijava))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        if (txtPretraga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite parametar!");
            return;
        }
                
        try {
            Student s = new Student(-1, txtPretraga.getText(), new Date(), "", null);
            ArrayList<Student> listaPronadjenih = KlijentKontroler.getInstance().nadjiStudente(s);
            tblStudenti.setModel(new ModelTabeleStudent(listaPronadjenih));
            
            if (listaPronadjenih.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem ne može da nađe studente po zadatoj vrednosti");
                    txtPretraga.setText(null);
                    ArrayList<Student> praznaLista = new ArrayList<>();
                    tblStudenti.setModel(new ModelTabeleStudent(praznaLista));
            } else {
                    JOptionPane.showMessageDialog(this, "Sistem je našao studente po zadatoj vrednosti");
                    tblStudenti.setModel(new ModelTabeleStudent(listaPronadjenih));
            }     
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Sistem ne može da nađe studente po zadatoj vrednosti");
        }
        
        txtPretraga.setText(null);
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnResetujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetujActionPerformed
        try {
            txtPretraga.setText(null);
            tblStudenti.setModel(new ModelTabeleStudent());
        } catch (Exception ex) {
            Logger.getLogger(FormaPretragaStudenata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResetujActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        int red = tblStudenti.getSelectedRow();
        
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita studenta! Izaberite red!");
        } else {
            ModelTabeleStudent mts = (ModelTabeleStudent) tblStudenti.getModel();
            Student student = mts.getStudent(red);
            try {
                Student s = new Student(student.getStudentID(), "", new Date(), "", null);
                Student parametar = KlijentKontroler.getInstance().ucitajStudenta(s);
                JOptionPane.showMessageDialog(this, "Sistem je učitao studenta!");
                new FormaIzmenaStudenta(this, true, parametar).setVisible(true);
            } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita studenta!");
            }
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed
        int red = tblStudenti.getSelectedRow();
        
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita studenta! Izaberite red!");
        } else {
            ModelTabeleStudent mts = (ModelTabeleStudent) tblStudenti.getModel();
            Student student = mts.getStudent(red);
            try {
                Student s = new Student(student.getStudentID(), "", new Date(), "", null);
                Student parametar = KlijentKontroler.getInstance().ucitajStudenta(s);
                JOptionPane.showMessageDialog(this, "Sistem je učitao studenta!");
                new FormaPrijavaIspita(this, true, parametar).setVisible(true);
            } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita studenta!");
            }
        }
    }//GEN-LAST:event_btnPrijavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaStudenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaStudenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaStudenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaStudenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormaPretragaStudenata dialog = new FormaPretragaStudenata(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrijava;
    private javax.swing.JButton btnResetuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudenti;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        try {
            tblStudenti.setModel(new ModelTabeleStudent());
        } catch (Exception ex) {
            Logger.getLogger(FormaPretragaStudenata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void osveziTabelu() throws Exception {
        tblStudenti.setModel(new ModelTabeleStudent());
    }
}
