/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forma;

import domen.Mesto;
import domen.Student;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logika.KlijentKontroler;

/**
 *
 * @author mihailomitrovic
 */
public class FormaIzmenaStudenta extends javax.swing.JDialog {

    Student student;
    
    /**
     * Creates new form FormaDetaljiStudenta
     */
    public FormaIzmenaStudenta(JDialog parent, boolean modal, Student student) throws Exception {
        super(parent, modal);
        initComponents();
        this.student = student;
        setLocationRelativeTo(parent);
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDatumRodjenja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKontakt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbMesto = new javax.swing.JComboBox();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Studentska služba - Izmena studenta");

        jLabel2.setText("Ime i prezime:");

        jLabel5.setText("Datum rođenja:");

        jLabel3.setText("Kontakt:");

        jLabel4.setText("Mesto:");

        cmbMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmeni.setText("Izmeni studenta");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzmeni))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(61, 61, 61))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImePrezime)
                            .addComponent(txtKontakt)
                            .addComponent(txtDatumRodjenja)
                            .addComponent(cmbMesto, javax.swing.GroupLayout.Alignment.TRAILING, 0, 278, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzmeni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        String imePrezime = txtImePrezime.getText();
        String datum = txtDatumRodjenja.getText();
        String kontakt = txtKontakt.getText();
        Mesto mesto = (Mesto) cmbMesto.getSelectedItem();

        if (imePrezime.isEmpty() || datum.isEmpty() || kontakt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna!");
            return;
        }
        
        if (!imePrezime.contains(" ")) {
            JOptionPane.showMessageDialog(this, "Moraju se uneti i ime i prezime!");
            return;        
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datumRodjenja;
        try {
            datumRodjenja = sdf.parse(datum);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Format datuma nije ispravan!");
            return;
        }
        
        if (datumRodjenja.after(new Date())) {
            JOptionPane.showMessageDialog(this, "Datum rođenja ne može biti posle današnjeg datuma");
            return;
        }
        
        if (txtKontakt.getText().length() > 9) {
            JOptionPane.showMessageDialog(this, "Kontakt telefon ne može imati više od 9 cifara!");
            return;        
        }
        
        for (int i = 0; i < txtKontakt.getText().length(); i++) {
            if (Character.isLetter(txtKontakt.getText().charAt(i))) {
                JOptionPane.showMessageDialog(this, "Kontakt telefon ne može sadržati cifre!");
                return;
            }
        }

        try {
            student.setImePrezime(imePrezime);
            student.setDatumRodjenja(datumRodjenja);
            student.setKontakt(kontakt);
            student.setMesto(mesto);
            
            KlijentKontroler.getInstance().izmeniStudenta(student);
            JOptionPane.showMessageDialog(this, "Sistem je izmenio studenta!");
            FormaPretragaStudenata fps = (FormaPretragaStudenata) getParent();
            fps.osveziTabelu();
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da izmeni studenta!");
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaIzmenaStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    FormaIzmenaStudenta dialog = new FormaIzmenaStudenta(new JDialog(), true, new Student());
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FormaIzmenaStudenta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbMesto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDatumRodjenja;
    private javax.swing.JTextField txtImePrezime;
    private javax.swing.JTextField txtKontakt;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws Exception {
        txtImePrezime.setText(student.getImePrezime());
        txtKontakt.setText(student.getKontakt());
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumRodjenja.setText(sdf.format(student.getDatumRodjenja()));
        
        cmbMesto.removeAllItems();
        for (Mesto mesto : KlijentKontroler.getInstance().ucitajListuMesta()) {
            cmbMesto.addItem(mesto);
        }
        cmbMesto.getModel().setSelectedItem(student.getMesto());  
    }
}
