/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forma;

import domen.PrijavaIspita;
import domen.RacunPrijaveIspita;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logika.KlijentKontroler;

/**
 *
 * @author mihailomitrovic
 */
public class FormaRacun extends javax.swing.JDialog {

    PrijavaIspita prijava;
    
    /**
     * Creates new form FormaRacun
     */
    public FormaRacun(JDialog parent, boolean modal, PrijavaIspita prijava) {
        super(parent, modal);
        initComponents();
        this.prijava = prijava;
        setLocationRelativeTo(parent);
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRacun = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSluzbenik = new javax.swing.JLabel();
        lblVreme = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        lblCena = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblUkupnaCena = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDatum1 = new javax.swing.JLabel();
        txtDatumRacuna = new javax.swing.JTextField();
        btnIzdaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Studentska služba - Račun");

        panelRacun.setBackground(new java.awt.Color(255, 255, 255));
        panelRacun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel1.setText("========== FISKALNI RAČUN ==========");

        lblSluzbenik.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lblSluzbenik.setText("Službenik: ???");

        lblVreme.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lblVreme.setText("Datum:");

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel2.setText("-----------------------------------------");

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setText("Naziv");

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel4.setText("Artikli");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel5.setText("====================================");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel6.setText("Količina");

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Cena");

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel8.setText("1");

        lblNaziv.setText("???");

        lblCena.setText("???");

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel9.setText("-----------------------------------------");

        lblDatum.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lblDatum.setText("Datum prijave: ???");

        lblUkupnaCena.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lblUkupnaCena.setText("???");

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jLabel10.setText("====== KRAJ FISKALNOG RAČUNA ======");

        lblDatum1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lblDatum1.setText("Ukupna cena:");

        javax.swing.GroupLayout panelRacunLayout = new javax.swing.GroupLayout(panelRacun);
        panelRacun.setLayout(panelRacunLayout);
        panelRacunLayout.setHorizontalGroup(
            panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRacunLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(lblDatum)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addGroup(panelRacunLayout.createSequentialGroup()
                        .addGroup(panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRacunLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRacunLayout.createSequentialGroup()
                                .addComponent(lblNaziv)
                                .addGap(36, 36, 36)))
                        .addGroup(panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCena, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel5)
                    .addGroup(panelRacunLayout.createSequentialGroup()
                        .addComponent(lblDatum1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUkupnaCena))
                    .addComponent(jLabel2)
                    .addGroup(panelRacunLayout.createSequentialGroup()
                        .addComponent(lblVreme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatumRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSluzbenik)
                    .addComponent(jLabel1))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelRacunLayout.setVerticalGroup(
            panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRacunLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(lblSluzbenik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVreme)
                    .addComponent(txtDatumRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblNaziv)
                    .addComponent(lblCena))
                .addGap(18, 18, 18)
                .addComponent(lblDatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkupnaCena)
                    .addComponent(lblDatum1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18))
        );

        btnIzdaj.setText("Izdaj račun");
        btnIzdaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzdajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzdaj)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzdaj)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzdajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzdajActionPerformed
        String datum = txtDatumRacuna.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        
        try {
            Date datumRacuna = sdf.parse(datum);
            
            if (datum.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti datum!");
            return;
            }
            
                    
            Calendar c1 = Calendar.getInstance();
            c1.setTime(datumRacuna);
            Calendar c2 = Calendar.getInstance();
            c2.setTime(new Date());     
                      
            if (c1.get(Calendar.DAY_OF_MONTH) != c2.get(Calendar.DAY_OF_MONTH) || c1.get(Calendar.MONTH) != c2.get(Calendar.MONTH) || c1.get(Calendar.YEAR) != c2.get(Calendar.YEAR)) {
                JOptionPane.showMessageDialog(this, "Unesite današnji datum!");
                return;
            }

            
            Object[] opcije = { "Da", "Ne" };
            int izbor = JOptionPane.showOptionDialog(null, "Da li želite da izdate račun?", "Izdavanje računa",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcije, opcije[0]);
        
            if (izbor == 0) {
                try {
                    KlijentKontroler.getInstance().zapamtiRacunPrijaveIspita(prijava);
                    JOptionPane.showMessageDialog(this, "Sistem je zapamtio račun!");
                    FormaPretragaPrijava forma = (FormaPretragaPrijava) getParent();
                    forma.osveziTabelu();
                    this.dispose();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti račun!");
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(FormaRacun.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnIzdajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormaRacun dialog = new FormaRacun(new JDialog(), true, new PrijavaIspita());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void srediFormu() {
        SimpleDateFormat sdfVreme = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
        lblNaziv.setText(prijava.getIspit().toString());
        lblCena.setText(prijava.getIspit().getCena() + ".00");
        SimpleDateFormat sdfDatum = new SimpleDateFormat("dd.MM.yyyy");
        lblDatum.setText("Datum: " + sdfDatum.format(prijava.getDatumPrijave()));
        lblUkupnaCena.setText(prijava.getIspit().getCena() + ".00");
        lblSluzbenik.setText("Službenik: " + prijava.getSluzbenik().getImePrezime());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzdaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDatum1;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblSluzbenik;
    private javax.swing.JLabel lblUkupnaCena;
    private javax.swing.JLabel lblVreme;
    private javax.swing.JPanel panelRacun;
    private javax.swing.JTextField txtDatumRacuna;
    // End of variables declaration//GEN-END:variables
}
