/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forma;

import domen.Ispit;
import domen.Student;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.KlijentKontroler;
import model.ModelTabeleInformacija;
import model.ModelTabeleIspit;
import model.ModelTabelePrijava;

/**
 *
 * @author mihailomitrovic
 */
public class FormaPretragaIspita extends javax.swing.JDialog {

    private static String poruka = "";

    public static void setPoruka(String poruka) {
        FormaPretragaIspita.poruka = poruka;
    }
    
    /**
     * Creates new form FormaPretragaIspita
     */
    public FormaPretragaIspita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIspiti = new javax.swing.JTable();
        btnPretraži = new javax.swing.JButton();
        btnResetuj = new javax.swing.JButton();
        btnPrikaziInformacije = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Studentska služba - Ispiti");

        jLabel1.setText("Naziv ispita:");

        tblIspiti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIspiti);

        btnPretraži.setText("Pretraži");
        btnPretraži.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretražiActionPerformed(evt);
            }
        });

        btnResetuj.setText("Resetuj");
        btnResetuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetujActionPerformed(evt);
            }
        });

        btnPrikaziInformacije.setText("Prikaži informacije");
        btnPrikaziInformacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziInformacijeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPretraga))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPretraži)
                                .addGap(5, 5, 5)
                                .addComponent(btnResetuj))
                            .addComponent(btnPrikaziInformacije, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraži)
                    .addComponent(btnResetuj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrikaziInformacije)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretražiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretražiActionPerformed
        if (txtPretraga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite parametar za pretragu!");
            return;
        }
        
        try {
            Ispit i = new Ispit(-1, txtPretraga.getText(), "", 0, 0);
            ArrayList<Ispit> listaPronadjenih = KlijentKontroler.getInstance().nadjiIspite(i);
            tblIspiti.setModel(new ModelTabeleInformacija(listaPronadjenih));
            
            if (listaPronadjenih.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem ne može da nađe ispite po zadatoj vrednosti!");
                    txtPretraga.setText(null);
                    ArrayList<Ispit> praznaLista = new ArrayList<>();
                    tblIspiti.setModel(new ModelTabeleInformacija(praznaLista));
            } else {
                    JOptionPane.showMessageDialog(this, "Sistem je našao ispite po zadatoj vrednosti!");
                    tblIspiti.setModel(new ModelTabeleInformacija(listaPronadjenih));
            }     
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe ispite po zadatoj vrednosti!");
        }
        
        txtPretraga.setText(null);
    }//GEN-LAST:event_btnPretražiActionPerformed

    private void btnResetujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetujActionPerformed
        txtPretraga.setText(null);
        osveziTabelu();
    }//GEN-LAST:event_btnResetujActionPerformed

    private void btnPrikaziInformacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziInformacijeActionPerformed
        int red = tblIspiti.getSelectedRow();
        
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita ispit! Izaberite red!");
        } else {
            ModelTabeleInformacija mti = (ModelTabeleInformacija) tblIspiti.getModel();
            Ispit ispit = mti.getIspit(red);
            try {
                Ispit i = new Ispit(ispit.getIspitID(), "", "", 0, 0);
                Ispit parametar = KlijentKontroler.getInstance().ucitajIspit(i);
                JOptionPane.showMessageDialog(this, "Sistem je učitao ispit!");
                new FormaInformacije(this, true, parametar).setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita ispit!");
            }
        }
    }//GEN-LAST:event_btnPrikaziInformacijeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaIspita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaIspita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaIspita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPretragaIspita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormaPretragaIspita dialog = new FormaPretragaIspita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretraži;
    private javax.swing.JButton btnPrikaziInformacije;
    private javax.swing.JButton btnResetuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIspiti;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            tblIspiti.setModel(new ModelTabeleInformacija());
        } catch (Exception ex) {
            Logger.getLogger(FormaPretragaPrijava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void osveziTabelu() {
        try {
            tblIspiti.setModel(new ModelTabeleInformacija());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da osveži tabelu!");
        }
    }
}
